// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apps.proto

package backend

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Search
type SearchAppsRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortField            int64    `protobuf:"varint,3,opt,name=sortField,proto3" json:"sortField,omitempty"`
	SortOrder            int32    `protobuf:"varint,4,opt,name=sortOrder,proto3" json:"sortOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchAppsRequest) Reset()         { *m = SearchAppsRequest{} }
func (m *SearchAppsRequest) String() string { return proto.CompactTextString(m) }
func (*SearchAppsRequest) ProtoMessage()    {}
func (*SearchAppsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb8c98b30758e0ce, []int{0}
}

func (m *SearchAppsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchAppsRequest.Unmarshal(m, b)
}
func (m *SearchAppsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchAppsRequest.Marshal(b, m, deterministic)
}
func (m *SearchAppsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchAppsRequest.Merge(m, src)
}
func (m *SearchAppsRequest) XXX_Size() int {
	return xxx_messageInfo_SearchAppsRequest.Size(m)
}
func (m *SearchAppsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchAppsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchAppsRequest proto.InternalMessageInfo

func (m *SearchAppsRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *SearchAppsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchAppsRequest) GetSortField() int64 {
	if m != nil {
		return m.SortField
	}
	return 0
}

func (m *SearchAppsRequest) GetSortOrder() int32 {
	if m != nil {
		return m.SortOrder
	}
	return 0
}

type AppsElasticResponse struct {
	Pagination           *PaginationResponse   `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Apps                 []*AppElasticResponse `protobuf:"bytes,2,rep,name=apps,proto3" json:"apps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AppsElasticResponse) Reset()         { *m = AppsElasticResponse{} }
func (m *AppsElasticResponse) String() string { return proto.CompactTextString(m) }
func (*AppsElasticResponse) ProtoMessage()    {}
func (*AppsElasticResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb8c98b30758e0ce, []int{1}
}

func (m *AppsElasticResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppsElasticResponse.Unmarshal(m, b)
}
func (m *AppsElasticResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppsElasticResponse.Marshal(b, m, deterministic)
}
func (m *AppsElasticResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppsElasticResponse.Merge(m, src)
}
func (m *AppsElasticResponse) XXX_Size() int {
	return xxx_messageInfo_AppsElasticResponse.Size(m)
}
func (m *AppsElasticResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppsElasticResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppsElasticResponse proto.InternalMessageInfo

func (m *AppsElasticResponse) GetPagination() *PaginationResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *AppsElasticResponse) GetApps() []*AppElasticResponse {
	if m != nil {
		return m.Apps
	}
	return nil
}

type AppElasticResponse struct {
	AchievementsCounts   int32             `protobuf:"varint,1,opt,name=achievementsCounts,proto3" json:"achievementsCounts,omitempty"`
	FloatachievementsAvg float32           `protobuf:"fixed32,2,opt,name=floatachievementsAvg,proto3" json:"floatachievementsAvg,omitempty"`
	AchievementIcons     map[string]string `protobuf:"bytes,3,rep,name=achievementIcons,proto3" json:"achievementIcons,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Aliases              []string          `protobuf:"bytes,4,rep,name=aliases,proto3" json:"aliases,omitempty"`
	Categories           []int32           `protobuf:"varint,5,rep,packed,name=categories,proto3" json:"categories,omitempty"`
	Developers           []int32           `protobuf:"varint,6,rep,packed,name=developers,proto3" json:"developers,omitempty"`
	Followers            int32             `protobuf:"varint,7,opt,name=followers,proto3" json:"followers,omitempty"`
	Genres               []int32           `protobuf:"varint,8,rep,packed,name=genres,proto3" json:"genres,omitempty"`
	Icon                 string            `protobuf:"bytes,9,opt,name=icon,proto3" json:"icon,omitempty"`
	Id                   int32             `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	NameMarked           string            `protobuf:"bytes,12,opt,name=nameMarked,proto3" json:"nameMarked,omitempty"`
	Platforms            []string          `protobuf:"bytes,13,rep,name=platforms,proto3" json:"platforms,omitempty"`
	Players              int32             `protobuf:"varint,14,opt,name=players,proto3" json:"players,omitempty"`
	Prices               map[string]*Price `protobuf:"bytes,15,rep,name=prices,proto3" json:"prices,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Publishers           []int32           `protobuf:"varint,16,rep,packed,name=publishers,proto3" json:"publishers,omitempty"`
	ReleaseDate          int64             `protobuf:"varint,17,opt,name=releaseDate,proto3" json:"releaseDate,omitempty"`
	Score                float32           `protobuf:"fixed32,18,opt,name=score,proto3" json:"score,omitempty"`
	SearchScore          float32           `protobuf:"fixed32,19,opt,name=searchScore,proto3" json:"searchScore,omitempty"`
	Tags                 []int32           `protobuf:"varint,20,rep,packed,name=tags,proto3" json:"tags,omitempty"`
	Type                 string            `protobuf:"bytes,21,opt,name=type,proto3" json:"type,omitempty"`
	Trend                float32           `protobuf:"fixed32,22,opt,name=trend,proto3" json:"trend,omitempty"`
	WishlistAvg          float32           `protobuf:"fixed32,23,opt,name=wishlistAvg,proto3" json:"wishlistAvg,omitempty"`
	WishlistCount        int32             `protobuf:"varint,24,opt,name=wishlistCount,proto3" json:"wishlistCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AppElasticResponse) Reset()         { *m = AppElasticResponse{} }
func (m *AppElasticResponse) String() string { return proto.CompactTextString(m) }
func (*AppElasticResponse) ProtoMessage()    {}
func (*AppElasticResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb8c98b30758e0ce, []int{2}
}

func (m *AppElasticResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppElasticResponse.Unmarshal(m, b)
}
func (m *AppElasticResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppElasticResponse.Marshal(b, m, deterministic)
}
func (m *AppElasticResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppElasticResponse.Merge(m, src)
}
func (m *AppElasticResponse) XXX_Size() int {
	return xxx_messageInfo_AppElasticResponse.Size(m)
}
func (m *AppElasticResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppElasticResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppElasticResponse proto.InternalMessageInfo

func (m *AppElasticResponse) GetAchievementsCounts() int32 {
	if m != nil {
		return m.AchievementsCounts
	}
	return 0
}

func (m *AppElasticResponse) GetFloatachievementsAvg() float32 {
	if m != nil {
		return m.FloatachievementsAvg
	}
	return 0
}

func (m *AppElasticResponse) GetAchievementIcons() map[string]string {
	if m != nil {
		return m.AchievementIcons
	}
	return nil
}

func (m *AppElasticResponse) GetAliases() []string {
	if m != nil {
		return m.Aliases
	}
	return nil
}

func (m *AppElasticResponse) GetCategories() []int32 {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *AppElasticResponse) GetDevelopers() []int32 {
	if m != nil {
		return m.Developers
	}
	return nil
}

func (m *AppElasticResponse) GetFollowers() int32 {
	if m != nil {
		return m.Followers
	}
	return 0
}

func (m *AppElasticResponse) GetGenres() []int32 {
	if m != nil {
		return m.Genres
	}
	return nil
}

func (m *AppElasticResponse) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *AppElasticResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AppElasticResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppElasticResponse) GetNameMarked() string {
	if m != nil {
		return m.NameMarked
	}
	return ""
}

func (m *AppElasticResponse) GetPlatforms() []string {
	if m != nil {
		return m.Platforms
	}
	return nil
}

func (m *AppElasticResponse) GetPlayers() int32 {
	if m != nil {
		return m.Players
	}
	return 0
}

func (m *AppElasticResponse) GetPrices() map[string]*Price {
	if m != nil {
		return m.Prices
	}
	return nil
}

func (m *AppElasticResponse) GetPublishers() []int32 {
	if m != nil {
		return m.Publishers
	}
	return nil
}

func (m *AppElasticResponse) GetReleaseDate() int64 {
	if m != nil {
		return m.ReleaseDate
	}
	return 0
}

func (m *AppElasticResponse) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *AppElasticResponse) GetSearchScore() float32 {
	if m != nil {
		return m.SearchScore
	}
	return 0
}

func (m *AppElasticResponse) GetTags() []int32 {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *AppElasticResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AppElasticResponse) GetTrend() float32 {
	if m != nil {
		return m.Trend
	}
	return 0
}

func (m *AppElasticResponse) GetWishlistAvg() float32 {
	if m != nil {
		return m.WishlistAvg
	}
	return 0
}

func (m *AppElasticResponse) GetWishlistCount() int32 {
	if m != nil {
		return m.WishlistCount
	}
	return 0
}

// List
type ListAppsRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortField            int64    `protobuf:"varint,3,opt,name=sortField,proto3" json:"sortField,omitempty"`
	SortOrder            int32    `protobuf:"varint,4,opt,name=sortOrder,proto3" json:"sortOrder,omitempty"`
	Ids                  []int32  `protobuf:"varint,5,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Tags                 []int32  `protobuf:"varint,6,rep,packed,name=tags,proto3" json:"tags,omitempty"`
	Genres               []int32  `protobuf:"varint,7,rep,packed,name=genres,proto3" json:"genres,omitempty"`
	Categories           []int32  `protobuf:"varint,8,rep,packed,name=categories,proto3" json:"categories,omitempty"`
	Developers           []int32  `protobuf:"varint,9,rep,packed,name=developers,proto3" json:"developers,omitempty"`
	Publishers           []int32  `protobuf:"varint,10,rep,packed,name=publishers,proto3" json:"publishers,omitempty"`
	Platforms            []string `protobuf:"bytes,11,rep,name=platforms,proto3" json:"platforms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAppsRequest) Reset()         { *m = ListAppsRequest{} }
func (m *ListAppsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAppsRequest) ProtoMessage()    {}
func (*ListAppsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb8c98b30758e0ce, []int{3}
}

func (m *ListAppsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAppsRequest.Unmarshal(m, b)
}
func (m *ListAppsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAppsRequest.Marshal(b, m, deterministic)
}
func (m *ListAppsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAppsRequest.Merge(m, src)
}
func (m *ListAppsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAppsRequest.Size(m)
}
func (m *ListAppsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAppsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAppsRequest proto.InternalMessageInfo

func (m *ListAppsRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListAppsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListAppsRequest) GetSortField() int64 {
	if m != nil {
		return m.SortField
	}
	return 0
}

func (m *ListAppsRequest) GetSortOrder() int32 {
	if m != nil {
		return m.SortOrder
	}
	return 0
}

func (m *ListAppsRequest) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ListAppsRequest) GetTags() []int32 {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ListAppsRequest) GetGenres() []int32 {
	if m != nil {
		return m.Genres
	}
	return nil
}

func (m *ListAppsRequest) GetCategories() []int32 {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *ListAppsRequest) GetDevelopers() []int32 {
	if m != nil {
		return m.Developers
	}
	return nil
}

func (m *ListAppsRequest) GetPublishers() []int32 {
	if m != nil {
		return m.Publishers
	}
	return nil
}

func (m *ListAppsRequest) GetPlatforms() []string {
	if m != nil {
		return m.Platforms
	}
	return nil
}

type AppsMongoResponse struct {
	Pagination           *PaginationResponse `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Apps                 []*AppMongoResponse `protobuf:"bytes,2,rep,name=apps,proto3" json:"apps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AppsMongoResponse) Reset()         { *m = AppsMongoResponse{} }
func (m *AppsMongoResponse) String() string { return proto.CompactTextString(m) }
func (*AppsMongoResponse) ProtoMessage()    {}
func (*AppsMongoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb8c98b30758e0ce, []int{4}
}

func (m *AppsMongoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppsMongoResponse.Unmarshal(m, b)
}
func (m *AppsMongoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppsMongoResponse.Marshal(b, m, deterministic)
}
func (m *AppsMongoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppsMongoResponse.Merge(m, src)
}
func (m *AppsMongoResponse) XXX_Size() int {
	return xxx_messageInfo_AppsMongoResponse.Size(m)
}
func (m *AppsMongoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppsMongoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppsMongoResponse proto.InternalMessageInfo

func (m *AppsMongoResponse) GetPagination() *PaginationResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *AppsMongoResponse) GetApps() []*AppMongoResponse {
	if m != nil {
		return m.Apps
	}
	return nil
}

type AppMongoResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppMongoResponse) Reset()         { *m = AppMongoResponse{} }
func (m *AppMongoResponse) String() string { return proto.CompactTextString(m) }
func (*AppMongoResponse) ProtoMessage()    {}
func (*AppMongoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb8c98b30758e0ce, []int{5}
}

func (m *AppMongoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppMongoResponse.Unmarshal(m, b)
}
func (m *AppMongoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppMongoResponse.Marshal(b, m, deterministic)
}
func (m *AppMongoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppMongoResponse.Merge(m, src)
}
func (m *AppMongoResponse) XXX_Size() int {
	return xxx_messageInfo_AppMongoResponse.Size(m)
}
func (m *AppMongoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppMongoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppMongoResponse proto.InternalMessageInfo

func (m *AppMongoResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AppMongoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*SearchAppsRequest)(nil), "backend.SearchAppsRequest")
	proto.RegisterType((*AppsElasticResponse)(nil), "backend.AppsElasticResponse")
	proto.RegisterType((*AppElasticResponse)(nil), "backend.AppElasticResponse")
	proto.RegisterMapType((map[string]string)(nil), "backend.AppElasticResponse.AchievementIconsEntry")
	proto.RegisterMapType((map[string]*Price)(nil), "backend.AppElasticResponse.PricesEntry")
	proto.RegisterType((*ListAppsRequest)(nil), "backend.ListAppsRequest")
	proto.RegisterType((*AppsMongoResponse)(nil), "backend.AppsMongoResponse")
	proto.RegisterType((*AppMongoResponse)(nil), "backend.AppMongoResponse")
}

func init() { proto.RegisterFile("apps.proto", fileDescriptor_eb8c98b30758e0ce) }

var fileDescriptor_eb8c98b30758e0ce = []byte{
	// 774 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6a, 0xdb, 0x4a,
	0x10, 0x8e, 0x24, 0xff, 0xc4, 0xe3, 0xfc, 0x38, 0x9b, 0x9f, 0xb3, 0xc7, 0x27, 0x1c, 0x8c, 0x09,
	0x1c, 0xdf, 0x1c, 0x97, 0xba, 0x50, 0x4a, 0x0b, 0x2d, 0x26, 0x49, 0x21, 0xd0, 0xd0, 0xa0, 0x5c,
	0xf7, 0x62, 0x23, 0x8d, 0xed, 0x25, 0xb2, 0x56, 0xdd, 0x5d, 0x3b, 0xf8, 0xa2, 0xf4, 0xa2, 0x8f,
	0xd0, 0x87, 0xe9, 0x2b, 0xf4, 0xb1, 0xca, 0xae, 0x6c, 0x4b, 0xb2, 0x4d, 0x4a, 0x21, 0x57, 0xda,
	0xf9, 0xbe, 0x9d, 0xd9, 0xd1, 0xec, 0x7c, 0xb3, 0x00, 0x2c, 0x49, 0x54, 0x37, 0x91, 0x42, 0x0b,
	0x52, 0xbd, 0x63, 0xc1, 0x3d, 0xc6, 0x61, 0x73, 0x47, 0x8d, 0x98, 0xc4, 0x30, 0x85, 0xdb, 0x5f,
	0xe0, 0xe0, 0x16, 0x99, 0x0c, 0x46, 0xfd, 0x24, 0x51, 0x3e, 0x7e, 0x9e, 0xa0, 0xd2, 0xe4, 0x04,
	0x2a, 0x62, 0x30, 0x50, 0xa8, 0xa9, 0xd3, 0x72, 0x3a, 0x9e, 0x3f, 0xb7, 0xc8, 0x11, 0x94, 0x23,
	0x3e, 0xe6, 0x9a, 0xba, 0x2d, 0xa7, 0x53, 0xf6, 0x53, 0x83, 0x9c, 0x42, 0x4d, 0x09, 0xa9, 0xdf,
	0x73, 0x8c, 0x42, 0xea, 0x59, 0x87, 0x0c, 0x58, 0xb0, 0x1f, 0x65, 0x88, 0x92, 0x96, 0xac, 0x5f,
	0x06, 0xb4, 0xbf, 0x39, 0x70, 0x68, 0x4e, 0xbe, 0x8c, 0x98, 0xd2, 0x3c, 0xf0, 0x51, 0x25, 0x22,
	0x56, 0x48, 0xde, 0x00, 0x24, 0x6c, 0xc8, 0x63, 0xa6, 0xb9, 0x88, 0x6d, 0x16, 0xf5, 0xde, 0x3f,
	0xdd, 0xf9, 0x2f, 0x74, 0x6f, 0x96, 0xd4, 0xc2, 0xc1, 0xcf, 0x6d, 0x27, 0xcf, 0xa0, 0x64, 0x7e,
	0x9c, 0xba, 0x2d, 0xaf, 0xe0, 0xd6, 0x4f, 0x92, 0x95, 0x73, 0x7c, 0xbb, 0xb1, 0xfd, 0xb3, 0x0a,
	0x64, 0x9d, 0x24, 0x5d, 0x20, 0x2c, 0x18, 0x71, 0x9c, 0xe2, 0x18, 0x63, 0xad, 0xce, 0xc5, 0x24,
	0xd6, 0xca, 0x26, 0x53, 0xf6, 0x37, 0x30, 0xa4, 0x07, 0x47, 0x83, 0x48, 0x30, 0x9d, 0xa7, 0xfa,
	0xd3, 0xa1, 0xad, 0x96, 0xeb, 0x6f, 0xe4, 0xc8, 0x27, 0x68, 0xe4, 0xa0, 0xab, 0x40, 0xc4, 0x8a,
	0x7a, 0x36, 0xef, 0xe7, 0x8f, 0xe4, 0xdd, 0xed, 0xaf, 0xf8, 0x5c, 0xc6, 0x5a, 0xce, 0xfc, 0xb5,
	0x50, 0x84, 0x42, 0x95, 0x45, 0x9c, 0x29, 0x54, 0xb4, 0xd4, 0xf2, 0x3a, 0x35, 0x7f, 0x61, 0x92,
	0x7f, 0x01, 0x02, 0xa6, 0x71, 0x28, 0x24, 0x47, 0x45, 0xcb, 0x2d, 0xaf, 0x53, 0xf6, 0x73, 0x88,
	0xe1, 0x43, 0x9c, 0x62, 0x24, 0x12, 0x94, 0x8a, 0x56, 0x52, 0x3e, 0x43, 0xcc, 0xbd, 0x0e, 0x44,
	0x14, 0x89, 0x07, 0x43, 0x57, 0xd3, 0x7b, 0x5d, 0x02, 0xa6, 0x83, 0x86, 0x18, 0x4b, 0x54, 0x74,
	0xdb, 0x7a, 0xce, 0x2d, 0x42, 0xa0, 0xc4, 0x03, 0x11, 0xd3, 0x5a, 0xcb, 0xe9, 0xd4, 0x7c, 0xbb,
	0x26, 0x7b, 0xe0, 0xf2, 0x90, 0x82, 0x0d, 0xe1, 0xf2, 0xd0, 0xec, 0x89, 0xd9, 0x18, 0x69, 0x3d,
	0xdd, 0x63, 0xd6, 0x26, 0x1b, 0xf3, 0xbd, 0x66, 0xf2, 0x1e, 0x43, 0xba, 0x63, 0x99, 0x1c, 0x62,
	0xb2, 0x49, 0x22, 0xa6, 0x07, 0x42, 0x8e, 0x15, 0xdd, 0xb5, 0x7f, 0x9a, 0x01, 0xa6, 0x0a, 0x49,
	0xc4, 0x66, 0x26, 0xd3, 0x3d, 0x7b, 0xcc, 0xc2, 0x24, 0xef, 0xa0, 0x92, 0x48, 0x1e, 0xa0, 0xa2,
	0xfb, 0xb6, 0xe8, 0xff, 0x3d, 0x56, 0xf4, 0x1b, 0xbb, 0x33, 0x2d, 0xf5, 0xdc, 0xcd, 0x24, 0x96,
	0x4c, 0xee, 0x22, 0xae, 0x46, 0x26, 0x7a, 0x23, 0x2d, 0x53, 0x86, 0x90, 0x16, 0xd4, 0x25, 0x46,
	0xc8, 0x14, 0x5e, 0x30, 0x8d, 0xf4, 0xc0, 0xca, 0x23, 0x0f, 0x19, 0x51, 0xa9, 0x40, 0x48, 0xa4,
	0xc4, 0xb6, 0x49, 0x6a, 0x18, 0x3f, 0x65, 0x75, 0x79, 0x6b, 0xb9, 0x43, 0xcb, 0xe5, 0x21, 0x53,
	0x26, 0xcd, 0x86, 0x8a, 0x1e, 0xd9, 0x33, 0xed, 0xda, 0x62, 0xb3, 0x04, 0xe9, 0x71, 0x5a, 0x3a,
	0xb3, 0x36, 0xf1, 0xb5, 0xc4, 0x38, 0xa4, 0x27, 0x69, 0x7c, 0x6b, 0x98, 0xf8, 0x0f, 0x5c, 0x8d,
	0x22, 0xae, 0xb4, 0x69, 0xd1, 0xbf, 0xd2, 0xf8, 0x39, 0x88, 0x9c, 0xc1, 0xee, 0xc2, 0xb4, 0xfd,
	0x4d, 0xa9, 0x2d, 0x5d, 0x11, 0x6c, 0x9e, 0xc3, 0xf1, 0xc6, 0x5e, 0x24, 0x0d, 0xf0, 0xee, 0x71,
	0x66, 0xd5, 0x52, 0xf3, 0xcd, 0xd2, 0x24, 0x32, 0x65, 0xd1, 0x04, 0xad, 0x1e, 0x6a, 0x7e, 0x6a,
	0xbc, 0x76, 0x5f, 0x39, 0xcd, 0x2b, 0xa8, 0xe7, 0x6a, 0xbb, 0xc1, 0xf5, 0x2c, 0xef, 0x5a, 0xef,
	0xed, 0x65, 0x93, 0xc0, 0xb8, 0xe5, 0x42, 0xb5, 0x7f, 0xb8, 0xb0, 0xff, 0xc1, 0xfc, 0xc1, 0x9f,
	0x8e, 0x33, 0xef, 0x09, 0xc6, 0x99, 0xc9, 0x9c, 0x87, 0x0b, 0x35, 0x99, 0xe5, 0xf2, 0x96, 0x2a,
	0xb9, 0x5b, 0xca, 0xc4, 0x51, 0x2d, 0x88, 0xa3, 0x28, 0xc9, 0xed, 0xdf, 0x48, 0xb2, 0xb6, 0x26,
	0xc9, 0x62, 0x2f, 0xc2, 0x5a, 0x2f, 0x16, 0x44, 0x52, 0x5f, 0x11, 0x49, 0xfb, 0x2b, 0x1c, 0x98,
	0xa2, 0x5d, 0x8b, 0x78, 0x28, 0x9e, 0x66, 0x0e, 0xff, 0x5f, 0x98, 0xc3, 0x7f, 0xe7, 0xa5, 0x55,
	0x38, 0x65, 0x3e, 0x85, 0x5f, 0x42, 0x63, 0x95, 0x99, 0xcf, 0x06, 0x67, 0x6d, 0x36, 0xb8, 0xd9,
	0x6c, 0xe8, 0x7d, 0x77, 0xa0, 0x6e, 0x32, 0xbf, 0x45, 0x39, 0xe5, 0x01, 0x92, 0x0b, 0xa8, 0xa4,
	0x4f, 0x1a, 0x69, 0x2e, 0x8f, 0x5c, 0x7b, 0xe3, 0x9a, 0xa7, 0xf9, 0x74, 0x56, 0xdf, 0x9f, 0xf6,
	0x16, 0x79, 0x0b, 0x25, 0x43, 0x10, 0xba, 0xdc, 0xb7, 0xd2, 0x56, 0xcd, 0x66, 0x21, 0x42, 0x21,
	0xef, 0xf6, 0xd6, 0x5d, 0xc5, 0xbe, 0xaf, 0x2f, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x28,
	0xfa, 0xe9, 0x84, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppsServiceClient is the client API for AppsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppsServiceClient interface {
	Search(ctx context.Context, in *SearchAppsRequest, opts ...grpc.CallOption) (*AppsElasticResponse, error)
	Apps(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*AppsMongoResponse, error)
}

type appsServiceClient struct {
	cc *grpc.ClientConn
}

func NewAppsServiceClient(cc *grpc.ClientConn) AppsServiceClient {
	return &appsServiceClient{cc}
}

func (c *appsServiceClient) Search(ctx context.Context, in *SearchAppsRequest, opts ...grpc.CallOption) (*AppsElasticResponse, error) {
	out := new(AppsElasticResponse)
	err := c.cc.Invoke(ctx, "/backend.AppsService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appsServiceClient) Apps(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*AppsMongoResponse, error) {
	out := new(AppsMongoResponse)
	err := c.cc.Invoke(ctx, "/backend.AppsService/Apps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppsServiceServer is the server API for AppsService service.
type AppsServiceServer interface {
	Search(context.Context, *SearchAppsRequest) (*AppsElasticResponse, error)
	Apps(context.Context, *ListAppsRequest) (*AppsMongoResponse, error)
}

func RegisterAppsServiceServer(s *grpc.Server, srv AppsServiceServer) {
	s.RegisterService(&_AppsService_serviceDesc, srv)
}

func _AppsService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppsServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.AppsService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppsServiceServer).Search(ctx, req.(*SearchAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppsService_Apps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppsServiceServer).Apps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.AppsService/Apps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppsServiceServer).Apps(ctx, req.(*ListAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "backend.AppsService",
	HandlerType: (*AppsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _AppsService_Search_Handler,
		},
		{
			MethodName: "Apps",
			Handler:    _AppsService_Apps_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps.proto",
}
