// Code generated by protoc-gen-go. DO NOT EDIT.
// source: players.proto

package backend

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Search
type SearchPlayersRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortField            int64    `protobuf:"varint,3,opt,name=sortField,proto3" json:"sortField,omitempty"`
	SortOrder            int32    `protobuf:"varint,4,opt,name=sortOrder,proto3" json:"sortOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchPlayersRequest) Reset()         { *m = SearchPlayersRequest{} }
func (m *SearchPlayersRequest) String() string { return proto.CompactTextString(m) }
func (*SearchPlayersRequest) ProtoMessage()    {}
func (*SearchPlayersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5ab527c5a576078, []int{0}
}

func (m *SearchPlayersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPlayersRequest.Unmarshal(m, b)
}
func (m *SearchPlayersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPlayersRequest.Marshal(b, m, deterministic)
}
func (m *SearchPlayersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPlayersRequest.Merge(m, src)
}
func (m *SearchPlayersRequest) XXX_Size() int {
	return xxx_messageInfo_SearchPlayersRequest.Size(m)
}
func (m *SearchPlayersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPlayersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPlayersRequest proto.InternalMessageInfo

func (m *SearchPlayersRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *SearchPlayersRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchPlayersRequest) GetSortField() int64 {
	if m != nil {
		return m.SortField
	}
	return 0
}

func (m *SearchPlayersRequest) GetSortOrder() int32 {
	if m != nil {
		return m.SortOrder
	}
	return 0
}

type PlayersElasticResponse struct {
	Pagination           *PaginationResponse      `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Players              []*PlayerElasticResponse `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PlayersElasticResponse) Reset()         { *m = PlayersElasticResponse{} }
func (m *PlayersElasticResponse) String() string { return proto.CompactTextString(m) }
func (*PlayersElasticResponse) ProtoMessage()    {}
func (*PlayersElasticResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5ab527c5a576078, []int{1}
}

func (m *PlayersElasticResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayersElasticResponse.Unmarshal(m, b)
}
func (m *PlayersElasticResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayersElasticResponse.Marshal(b, m, deterministic)
}
func (m *PlayersElasticResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayersElasticResponse.Merge(m, src)
}
func (m *PlayersElasticResponse) XXX_Size() int {
	return xxx_messageInfo_PlayersElasticResponse.Size(m)
}
func (m *PlayersElasticResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayersElasticResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayersElasticResponse proto.InternalMessageInfo

func (m *PlayersElasticResponse) GetPagination() *PaginationResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *PlayersElasticResponse) GetPlayers() []*PlayerElasticResponse {
	if m != nil {
		return m.Players
	}
	return nil
}

type PlayerElasticResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerElasticResponse) Reset()         { *m = PlayerElasticResponse{} }
func (m *PlayerElasticResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerElasticResponse) ProtoMessage()    {}
func (*PlayerElasticResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5ab527c5a576078, []int{2}
}

func (m *PlayerElasticResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerElasticResponse.Unmarshal(m, b)
}
func (m *PlayerElasticResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerElasticResponse.Marshal(b, m, deterministic)
}
func (m *PlayerElasticResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerElasticResponse.Merge(m, src)
}
func (m *PlayerElasticResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerElasticResponse.Size(m)
}
func (m *PlayerElasticResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerElasticResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerElasticResponse proto.InternalMessageInfo

func (m *PlayerElasticResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayerElasticResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// List
type ListPlayersRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortField            int64    `protobuf:"varint,3,opt,name=sortField,proto3" json:"sortField,omitempty"`
	SortOrder            int32    `protobuf:"varint,4,opt,name=sortOrder,proto3" json:"sortOrder,omitempty"`
	Ids                  []int64  `protobuf:"varint,5,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPlayersRequest) Reset()         { *m = ListPlayersRequest{} }
func (m *ListPlayersRequest) String() string { return proto.CompactTextString(m) }
func (*ListPlayersRequest) ProtoMessage()    {}
func (*ListPlayersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5ab527c5a576078, []int{3}
}

func (m *ListPlayersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPlayersRequest.Unmarshal(m, b)
}
func (m *ListPlayersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPlayersRequest.Marshal(b, m, deterministic)
}
func (m *ListPlayersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPlayersRequest.Merge(m, src)
}
func (m *ListPlayersRequest) XXX_Size() int {
	return xxx_messageInfo_ListPlayersRequest.Size(m)
}
func (m *ListPlayersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPlayersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPlayersRequest proto.InternalMessageInfo

func (m *ListPlayersRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListPlayersRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListPlayersRequest) GetSortField() int64 {
	if m != nil {
		return m.SortField
	}
	return 0
}

func (m *ListPlayersRequest) GetSortOrder() int32 {
	if m != nil {
		return m.SortOrder
	}
	return 0
}

func (m *ListPlayersRequest) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type PlayersMongoResponse struct {
	Pagination           *PaginationResponse    `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Players              []*PlayerMongoResponse `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PlayersMongoResponse) Reset()         { *m = PlayersMongoResponse{} }
func (m *PlayersMongoResponse) String() string { return proto.CompactTextString(m) }
func (*PlayersMongoResponse) ProtoMessage()    {}
func (*PlayersMongoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5ab527c5a576078, []int{4}
}

func (m *PlayersMongoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayersMongoResponse.Unmarshal(m, b)
}
func (m *PlayersMongoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayersMongoResponse.Marshal(b, m, deterministic)
}
func (m *PlayersMongoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayersMongoResponse.Merge(m, src)
}
func (m *PlayersMongoResponse) XXX_Size() int {
	return xxx_messageInfo_PlayersMongoResponse.Size(m)
}
func (m *PlayersMongoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayersMongoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayersMongoResponse proto.InternalMessageInfo

func (m *PlayersMongoResponse) GetPagination() *PaginationResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *PlayersMongoResponse) GetPlayers() []*PlayerMongoResponse {
	if m != nil {
		return m.Players
	}
	return nil
}

type PlayerMongoResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerMongoResponse) Reset()         { *m = PlayerMongoResponse{} }
func (m *PlayerMongoResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerMongoResponse) ProtoMessage()    {}
func (*PlayerMongoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5ab527c5a576078, []int{5}
}

func (m *PlayerMongoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerMongoResponse.Unmarshal(m, b)
}
func (m *PlayerMongoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerMongoResponse.Marshal(b, m, deterministic)
}
func (m *PlayerMongoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerMongoResponse.Merge(m, src)
}
func (m *PlayerMongoResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerMongoResponse.Size(m)
}
func (m *PlayerMongoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerMongoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerMongoResponse proto.InternalMessageInfo

func (m *PlayerMongoResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayerMongoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*SearchPlayersRequest)(nil), "backend.SearchPlayersRequest")
	proto.RegisterType((*PlayersElasticResponse)(nil), "backend.PlayersElasticResponse")
	proto.RegisterType((*PlayerElasticResponse)(nil), "backend.PlayerElasticResponse")
	proto.RegisterType((*ListPlayersRequest)(nil), "backend.ListPlayersRequest")
	proto.RegisterType((*PlayersMongoResponse)(nil), "backend.PlayersMongoResponse")
	proto.RegisterType((*PlayerMongoResponse)(nil), "backend.PlayerMongoResponse")
}

func init() { proto.RegisterFile("players.proto", fileDescriptor_c5ab527c5a576078) }

var fileDescriptor_c5ab527c5a576078 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcf, 0x4e, 0xe3, 0x30,
	0x10, 0xc6, 0xeb, 0xa4, 0x7f, 0xd4, 0xe9, 0x6e, 0xb5, 0x9a, 0xed, 0x56, 0x51, 0xb7, 0xdd, 0x8d,
	0x72, 0xca, 0xa9, 0x87, 0x22, 0x21, 0x50, 0xaf, 0xc0, 0x01, 0x81, 0xa8, 0xdc, 0x27, 0x70, 0x13,
	0xb7, 0xb5, 0x48, 0xe3, 0x60, 0x1b, 0x24, 0x6e, 0xdc, 0x39, 0xc0, 0x33, 0xf0, 0xa4, 0xa8, 0x49,
	0xda, 0xd0, 0xd0, 0x03, 0x42, 0xbd, 0xd9, 0x33, 0xf3, 0xe5, 0x9b, 0xf9, 0x79, 0x02, 0x3f, 0x93,
	0x88, 0x3d, 0x72, 0xa5, 0x87, 0x89, 0x92, 0x46, 0x62, 0x63, 0xc6, 0x82, 0x5b, 0x1e, 0x87, 0xbd,
	0x1f, 0x7a, 0xc9, 0x14, 0x0f, 0xb3, 0xb0, 0xf7, 0x44, 0xa0, 0x33, 0xe5, 0x4c, 0x05, 0xcb, 0x49,
	0x56, 0x4e, 0xf9, 0xdd, 0x3d, 0xd7, 0x06, 0xbb, 0x50, 0x97, 0xf3, 0xb9, 0xe6, 0xc6, 0x21, 0x2e,
	0xf1, 0x6d, 0x9a, 0xdf, 0xb0, 0x03, 0xb5, 0x48, 0xac, 0x84, 0x71, 0x2c, 0x97, 0xf8, 0x35, 0x9a,
	0x5d, 0xb0, 0x0f, 0x4d, 0x2d, 0x95, 0xb9, 0x10, 0x3c, 0x0a, 0x1d, 0x3b, 0x15, 0x14, 0x81, 0x4d,
	0xf6, 0x46, 0x85, 0x5c, 0x39, 0xd5, 0x54, 0x57, 0x04, 0xbc, 0x17, 0x02, 0xdd, 0xdc, 0xfc, 0x3c,
	0x62, 0xda, 0x88, 0x80, 0x72, 0x9d, 0xc8, 0x58, 0x73, 0x1c, 0x03, 0x24, 0x6c, 0x21, 0x62, 0x66,
	0x84, 0x8c, 0xd3, 0x46, 0x5a, 0xa3, 0xbf, 0xc3, 0x7c, 0x92, 0xe1, 0x64, 0x9b, 0xda, 0x08, 0xe8,
	0x87, 0x72, 0x3c, 0x81, 0x46, 0x8e, 0xc0, 0xb1, 0x5c, 0xdb, 0x6f, 0x8d, 0xfe, 0x15, 0xca, 0x34,
	0x5e, 0x72, 0xa3, 0x9b, 0x72, 0x6f, 0x0c, 0x7f, 0xf6, 0x56, 0x60, 0x1b, 0x2c, 0x11, 0xe6, 0x40,
	0x2c, 0x11, 0x22, 0x42, 0x35, 0x66, 0x2b, 0x9e, 0xb2, 0x68, 0xd2, 0xf4, 0xec, 0xbd, 0x12, 0xc0,
	0x2b, 0xa1, 0xcd, 0x77, 0x78, 0xda, 0x07, 0xe0, 0x89, 0xbf, 0xc0, 0x16, 0xa1, 0x76, 0x6a, 0xae,
	0xed, 0xdb, 0x74, 0x7d, 0xf4, 0x9e, 0x09, 0x74, 0xf2, 0x76, 0xae, 0x65, 0xbc, 0x90, 0x87, 0xe1,
	0x7b, 0x5c, 0xe6, 0xdb, 0x2f, 0xf1, 0xdd, 0xf1, 0x2a, 0xe8, 0x9e, 0xc2, 0xef, 0x3d, 0xf9, 0xaf,
	0xb0, 0x1d, 0xbd, 0x11, 0x68, 0xe7, 0x83, 0x4c, 0xb9, 0x7a, 0x10, 0x01, 0xc7, 0x4b, 0xa8, 0x67,
	0xfb, 0x8b, 0x83, 0xad, 0xfd, 0xbe, 0x85, 0xee, 0xfd, 0x2f, 0x75, 0x57, 0x5e, 0x36, 0xaf, 0x82,
	0x67, 0x50, 0x5d, 0xbf, 0x1c, 0x16, 0x08, 0x3e, 0x3f, 0x64, 0x6f, 0x50, 0xfe, 0xce, 0xce, 0x18,
	0x5e, 0x65, 0x56, 0x4f, 0xff, 0xac, 0xa3, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x14, 0x52, 0x74,
	0xff, 0x81, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlayersServiceClient is the client API for PlayersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayersServiceClient interface {
	Search(ctx context.Context, in *SearchPlayersRequest, opts ...grpc.CallOption) (*PlayersElasticResponse, error)
	List(ctx context.Context, in *ListPlayersRequest, opts ...grpc.CallOption) (*PlayersMongoResponse, error)
}

type playersServiceClient struct {
	cc *grpc.ClientConn
}

func NewPlayersServiceClient(cc *grpc.ClientConn) PlayersServiceClient {
	return &playersServiceClient{cc}
}

func (c *playersServiceClient) Search(ctx context.Context, in *SearchPlayersRequest, opts ...grpc.CallOption) (*PlayersElasticResponse, error) {
	out := new(PlayersElasticResponse)
	err := c.cc.Invoke(ctx, "/backend.PlayersService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playersServiceClient) List(ctx context.Context, in *ListPlayersRequest, opts ...grpc.CallOption) (*PlayersMongoResponse, error) {
	out := new(PlayersMongoResponse)
	err := c.cc.Invoke(ctx, "/backend.PlayersService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayersServiceServer is the server API for PlayersService service.
type PlayersServiceServer interface {
	Search(context.Context, *SearchPlayersRequest) (*PlayersElasticResponse, error)
	List(context.Context, *ListPlayersRequest) (*PlayersMongoResponse, error)
}

func RegisterPlayersServiceServer(s *grpc.Server, srv PlayersServiceServer) {
	s.RegisterService(&_PlayersService_serviceDesc, srv)
}

func _PlayersService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPlayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayersServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.PlayersService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayersServiceServer).Search(ctx, req.(*SearchPlayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayersService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayersServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.PlayersService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayersServiceServer).List(ctx, req.(*ListPlayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlayersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "backend.PlayersService",
	HandlerType: (*PlayersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _PlayersService_Search_Handler,
		},
		{
			MethodName: "List",
			Handler:    _PlayersService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "players.proto",
}
