settings:
  files:
    outputs:
      status: false
      path: ""
      name: logs.txt
    logs:
      status: false
      path: ""
      name: logs.txt
    errors:
      status: false
      path: ""
      name: logs.txt
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 5001
  host: "localhost"
schema:
- name: Steam
  path: .
  commands:
    install:
      status: true
    build:
      status: false
    run:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    - yaml
    ignored_paths:
    - .git
    - node_modules
