# Build image
FROM golang:1.12-alpine AS build-env
WORKDIR /root/
COPY ./ ./
RUN apk update && apk add git
RUN cd ./cmd/steam && go mod tidy && CGO_ENABLED=0 GOOS=linux go build -a

 # Runtime image
FROM alpine:3.10 AS runtime-env
WORKDIR /root/
COPY --from=build-env /root/cmd/steam/steam ./
COPY ./cmd/crons/health-check.sh ./health-check.sh
RUN ["chmod", "+x", "health-check.sh"]
RUN apk update && apk add ca-certificates curl bash
CMD ["./steam"]
HEALTHCHECK --interval=60s --timeout=10s --start-period=30s --retries=2 CMD ./health-check.sh
