#!/bin/bash

CMD=${1:-"frontend"}

nodemon \
  --signal SIGHUP \
  --exec "cd ./cmd/$CMD/ && go run -ldflags \"-X main.version=$(git rev-parse --verify HEAD) -X main.commits=$(git rev-list --count master)\"" \
  "*.go"
