#!/bin/bash

CMD=${1:-"webserver"}

nodemon \
  --signal SIGHUP \
  --exec "go run -ldflags \"-X main.version=$(git rev-parse --verify HEAD) -X main.commits=$(git rev-list --count master)\"" \
  "./cmd/$CMD/main.go"
