schema:
  - name: Web Server
    path: .
    commands:
      install:
        status: true
        args: -ldflags "-X main.version=`git rev-parse --verify HEAD` -X main.commits=`git rev-list --count master`"
      run:
        status: true
      build:
        status: false
    watcher:
      paths:
        - ../../
      extensions:
        - go
      ignored_paths:
        - ../../.git
        - ../../node_modules
        - ../../vendor
        - ./assets