#!/bin/bash

rm -rf /tmp/gamedb

mkdir -p /tmp/gamedb/bins
mkdir -p /tmp/gamedb/pids
mkdir -p /tmp/gamedb/logs

#
cd $STEAM_PATH || exit 1

# Build and run
go build -o ./cmd/devenv/devenv ./cmd/devenv/*.go
./cmd/devenv/devenv >/dev/null &
ID=$!

# Launch lnav
lnav /tmp/gamedb/logs

# Hide output as ctrl-c will cause the go process to already be killed
kill $ID >/dev/null 2>&1
