package highcharts

type AutoGenerated struct {
	Chart struct {
		ZoomType        string `json:"zoomType"`
		PlotBorderWidth int    `json:"plotBorderWidth"`
		MarginLeft      int    `json:"marginLeft"`
	} `json:"chart"`
	Title struct {
		Text string `json:"text"`
	} `json:"title"`
	Subtitle struct {
		Text  string `json:"text"`
		Align string `json:"align"`
		X     int    `json:"x"`
	} `json:"subtitle"`
	XAxis struct {
		Title struct {
			Text string `json:"text"`
		} `json:"title"`
		Type       string   `json:"type"`
		Categories []string `json:"categories"`
	} `json:"xAxis"`
	YAxis struct {
		Title struct {
			Text string `json:"text"`
		} `json:"title"`
		Type          string `json:"type"`
		Min           int    `json:"min"`
		AllowDecimals bool   `json:"allowDecimals"`
	} `json:"yAxis"`
	Legend struct {
		Enabled bool `json:"enabled"`
	} `json:"legend"`
	Credits struct {
		Enabled bool `json:"enabled"`
	} `json:"credits"`
	Series []struct {
		Type  string    `json:"type"`
		Name  string    `json:"name"`
		Step  string    `json:"step"`
		Color string    `json:"color"`
		Data  []float64 `json:"data"`
	} `json:"series"`
	Annotations []struct {
		LabelOptions struct {
			BackgroundColor string `json:"backgroundColor"`
			VerticalAlign   string `json:"verticalAlign"`
			Y               int    `json:"y"`
		} `json:"labelOptions"`
		Labels []struct {
			Point struct {
				XAxis int     `json:"xAxis"`
				YAxis int     `json:"yAxis"`
				X     float64 `json:"x"`
				Y     int     `json:"y"`
			} `json:"point"`
			Text string `json:"text"`
		} `json:"labels"`
	} `json:"annotations"`
}
